[package]
name = "heatmap"
version = "0.1.3"
authors = ["Brian Martin <brayniac@gmail.com>"]
license = "MIT"
readme = "README.md"

homepage = "https://github.com/brayniac/heatmap"
documentation = "http://brayniac.github.io/heatmap"
repository = "https://github.com/brayniac/heatmap"

description = "heatmap storage, set of histograms"

keywords = [ "heatmap", "histogram", "percentile", "statistics", "stats" ]

[dependencies]
histogram = "*"
time = "*"
